name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v6

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 129.146.186.101
          username: zainab
          key: ${{ secrets.DEPLOY_KEY }}
          source: "index.html,style.css,code.js"
          target: "/home/zainab/htdocs/abc.sunztech.com/"
